### ISSUE TITLE
AsyncIO for getting images

### ISSUE THREAD

**Issue by juliomateoslangerak** [manics/omero-asyncio#1]
Hi,
If I understand well this is supposed to work for queries to the database...
Is there something like this, or will this work for getting pixel data?

J

**Comment by manics** [comment]
In _theory_ it should work with any `get*Service` since all the wrappers are created dynamically:
https://github.com/microscopepony/omero-asyncio/blob/master/omero_asyncio/omero_asyncio.py

**Comment by juliomateoslangerak** [comment]
Sweet!
I'm looking forward to give it a try
